#Global configuration
spring:

  application:
    name: pay-my-buddy2
    #H2 Configuration
    h2.console.enabled: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymybuddy2
    username: root
    password: pouledeau

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /paymybuddy2

#Log level configuration
logging:
  level:
    error: DEBUG
